### NUMPY: ARRAYS AND MATRICES

> NumPy is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrics, along with a libray of high-level mathematical functions to operate on these arrays. 

In [1]:
# importing required modules
import numpy as np

### Create arrays

In [23]:
# create ndarrays from lists
data1 = [11, 33, 22, 55, 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1))
print (arr1.shape, type(arr1.shape))
result = arr1.tolist()
print (result, len(result), type(result), id(result))

[11, 33, 22, 55, 44, 66] 6 <class 'list'> 2911153787648
[11 33 22 55 44 66] 6 <class 'numpy.ndarray'> 2911143716976
(6,) <class 'tuple'>
[11, 33, 22, 55, 44, 66] 6 <class 'list'> 2911149761280


In [24]:
# create ndarrays from tuples
data1 = (11, 33, 22, 55, 44, 66)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1))
print (arr1.shape, type(arr1.shape))

(11, 33, 22, 55, 44, 66) 6 <class 'tuple'> 2911146678208
[11 33 22 55 44 66] 6 <class 'numpy.ndarray'> 2911146677424
(6,) <class 'tuple'>


In [25]:
# create ndarrays from lists
data2 = [[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2))
print (arr2.shape, type(arr2.shape))
result = arr2.tolist()
print (result, len(result), type(result), id(result))

[[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]] 2 <class 'list'> 2911151317248
[[ 11  33  22  55  44  66]
 [100 200 300 400 500 700]] 2 <class 'numpy.ndarray'> 2911146678576
(2, 6) <class 'tuple'>
[[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]] 2 <class 'list'> 2911153756800


In [26]:
# create ndarrays from lists
data2 = [range(1, 5), range(11, 15)]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2))
print (arr2.shape, type(arr2.shape))
result = arr2.tolist()
print (result, len(result), type(result), id(result))

[range(1, 5), range(11, 15)] 2 <class 'list'> 2911151845056
[[ 1  2  3  4]
 [11 12 13 14]] 2 <class 'numpy.ndarray'> 2911153911632
(2, 4) <class 'tuple'>
[[1, 2, 3, 4], [11, 12, 13, 14]] 2 <class 'list'> 2911151105984


In [35]:
# create ndarrays from lists
data1 = [11, True, 33, False, 22, 55, 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, '55', 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, 55, 44.0, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, '55', 44.0, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, True, 33, False, 22, 55, 44, 66] 8 <class 'list'> 2911151277824
[11  1 33  0 22 55 44 66] 8 <class 'numpy.ndarray'> 2911152022896 int32

[11, True, 33, False, 22, '55', 44, 66] 8 <class 'list'> 2911150934400
['11' 'True' '33' 'False' '22' '55' '44' '66'] 8 <class 'numpy.ndarray'> 2911143716304 <U11

[11, True, 33, False, 22, 55, 44.0, 66] 8 <class 'list'> 2911142055744
[11.  1. 33.  0. 22. 55. 44. 66.] 8 <class 'numpy.ndarray'> 2911152022896 float64

[11, True, 33, False, 22, '55', 44.0, 66] 8 <class 'list'> 2911149997248
['11' 'True' '33' 'False' '22' '55' '44.0' '66'] 8 <class 'numpy.ndarray'> 2911143717840 <U32


In [42]:
# exmining arrays
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1, arr1.shape)
print (arr2, arr2.shape)
print (arr1.dtype, arr2.dtype)
print (arr1.shape, arr2.shape)
print (arr1.ndim, arr2.ndim)
print (arr1.size, arr2.size)    # returns the number of data items
print (len(arr1), len(arr2))    # returns the first dimension

[11 33 22 55 44 66] (6,)
[[ 1  2  3  4]
 [11 12 13 14]] (2, 4)
int32 int32
(6,) (2, 4)
1 2
6 8
6 2


### Create Special Arrays

In [52]:
arr1 = np.zeros(10)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype('int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).reshape(2, 5).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype(int).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156382384
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704368
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156382384
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147705040
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156382384
[[0 0 0 0 0]
 [0 0 0 0 0]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156382288
[[0 0 0 0 0]
 [0 0 0 0 0]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911147704944


In [53]:
arr1 = np.ones(10)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype('int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).reshape(2, 5).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype(int).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156383248
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147705040
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911159970960
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911147705040
[[1 1 1 1 1]
 [1 1 1 1 1]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156383440
[[1 1 1 1 1]
 [1 1 1 1 1]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911159970960


In [56]:
arr1 = np.zeros(10) + 5    # vector + scalar
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10) * 5    # vector * scalar
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911148477296
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156383632


In [59]:
arr1 = np.linspace(0, 1, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.linspace(0, 10, 11, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.linspace(0, 10, 11, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[0.   0.25 0.5  0.75 1.  ] 5 5 1 (5,) <class 'numpy.ndarray'> 2911156383344
[ 0  1  2  3  4  5  6  7  8  9 10] 11 11 1 (11,) <class 'numpy.ndarray'> 2911156382480
[ 0  1  2  3  4  5  6  7  8  9 10] 11 11 1 (11,) <class 'numpy.ndarray'> 2911156382288


In [62]:
arr1 = np.logspace(0, 3, 4)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.logspace(0, 3, 4, base = 2, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.logspace(0, 3, 4, base = 4, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[   1.   10.  100. 1000.] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148670768
[1 2 4 8] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148669808
[ 1  4 16 64] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148670768


In [67]:
print (np.zeros(20).reshape(5, 4).astype(int).tolist())
print (np.zeros(20).astype(int).reshape(5, 4).tolist())
print (np.zeros(20).astype(int).reshape(4, 5).tolist())

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


### Indexing and Slicing

In [75]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
print (arr1[3], arr1[-3], arr1[1], arr1[-5])    # indexing
print (arr1[3:], arr1[-3:], arr1[:4], arr1[:-2])    # slicing

[11 33 22 55 44 66]
55 55 33 33
[55 44 66] [55 44 66] [11 33 22 55] [11 33 22 55]


In [88]:
data1 = [11, 33, 22, 55, 44, 66, 88, 99, 77, 25, 32, 67, 44, 66, 34, 45]
arr2 = np.array(data1).reshape(4, 4)
print (arr2)
print (arr2[1][2], arr2[-3][-2], arr2[1, 2], arr2[-3, -2])    # indexing
print (arr2[1:3, :])    # slicing
print (arr2[:, 1:3])
print (arr2[1:3, 1:3])
print (arr2[-3:-1, -3:-1])

[[11 33 22 55]
 [44 66 88 99]
 [77 25 32 67]
 [44 66 34 45]]
88 88 88 88
[[44 66 88 99]
 [77 25 32 67]]
[[33 22]
 [66 88]
 [25 32]
 [66 34]]
[[66 88]
 [25 32]]
[[66 88]
 [25 32]]


### Views and Copies

In [91]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr1[2:5] = 100
print (arr1)

[11 33 22 55 44 66]
[ 11  33 100 100 100  66]


In [94]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr_view = arr1[2:5]
print (arr_view)
arr_view[:] = 999
print (arr1)
print (arr_view)
arr1[2:5] = 777
print (arr1)
print (arr_view)

[11 33 22 55 44 66]
[22 55 44]
[ 11  33 999 999 999  66]
[999 999 999]
[ 11  33 777 777 777  66]
[777 777 777]


In [96]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr_copy = arr1[2:5].copy()
print (arr_copy)
arr_copy[:] = 999
print (arr1)
print (arr_copy)
arr1[2:5] = 777
print (arr1)
print (arr_copy)

[11 33 22 55 44 66]
[22 55 44]
[11 33 22 55 44 66]
[999 999 999]
[ 11  33 777 777 777  66]
[999 999 999]


### Boolean Arrays

In [103]:
data1 = [11, 99, 88, 33, 22, 55, 44, 66, 77, 45]
arr1 = np.array(data1)
print (arr1 > 55)
print (arr1[arr1 > 55])
print (~(arr1 > 55))    # negation with ~ operator
print (arr1[~(arr1 > 55)])
print (arr1[arr1 <= 55])

[False  True  True False False False False  True  True False]
[99 88 66 77]
[ True False False  True  True  True  True False False  True]
[11 33 22 55 44 45]
[11 33 22 55 44 45]


In [110]:
data1 = [11, 99, 88, 30, 22, 55, 44, 66, 77, 45]
arr1 = np.array(data1)
print (arr1)
print (arr1 % 6 == 0)
print (arr1[arr1 % 6 == 0])
print ((arr1 % 2 == 0) & (arr1 % 3 == 0))
print (arr1[(arr1 % 2 == 0) & (arr1 % 3 == 0)])
print ((arr1 % 2 == 0) | (arr1 % 3 == 0))
print (arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)])

[11 99 88 30 22 55 44 66 77 45]
[False False False  True False False False  True False False]
[30 66]
[False False False  True False False False  True False False]
[30 66]
[False  True  True  True  True False  True  True False  True]
[99 88 30 22 44 66 45]


In [114]:
data1 = [22, 55, 44, 30, 22, 55, 44, 66, 22, 55]
arr1 = np.array(data1)
print (arr1)
print (np.unique(arr1))

[22 55 44 30 22 55 44 66 22 55]
[22 30 44 55 66]


In [121]:
data1 = ['bob', 'paul', 'jim', 'paul', 'bob', 'tim', 'bob']
arr1 = np.array(data1)
print (arr1)
print (arr1 == 'bob')
print (arr1[arr1 == 'bob'])
print (~(arr1 == 'bob'))
print (arr1[~(arr1 == 'bob')])
arr1[arr1 == 'bob'] = 'pat'
print (arr1)
print (np.unique(arr1))

['bob' 'paul' 'jim' 'paul' 'bob' 'tim' 'bob']
[ True False False False  True False  True]
['bob' 'bob' 'bob']
[False  True  True  True False  True False]
['paul' 'jim' 'paul' 'tim']
['pat' 'paul' 'jim' 'paul' 'pat' 'tim' 'pat']
['jim' 'pat' 'paul' 'tim']


In [122]:
list1 = np.zeros(20).tolist()
print (list1, type(list1))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] <class 'list'>


### Vectorized Operations