### NUMPY: ARRAYS AND MATRICES

> NumPy is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrics, along with a libray of high-level mathematical functions to operate on these arrays. 

In [1]:
# importing required modules
import numpy as np

### Create arrays

In [23]:
# create ndarrays from lists
data1 = [11, 33, 22, 55, 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1))
print (arr1.shape, type(arr1.shape))
result = arr1.tolist()
print (result, len(result), type(result), id(result))

[11, 33, 22, 55, 44, 66] 6 <class 'list'> 2911153787648
[11 33 22 55 44 66] 6 <class 'numpy.ndarray'> 2911143716976
(6,) <class 'tuple'>
[11, 33, 22, 55, 44, 66] 6 <class 'list'> 2911149761280


In [24]:
# create ndarrays from tuples
data1 = (11, 33, 22, 55, 44, 66)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1))
print (arr1.shape, type(arr1.shape))

(11, 33, 22, 55, 44, 66) 6 <class 'tuple'> 2911146678208
[11 33 22 55 44 66] 6 <class 'numpy.ndarray'> 2911146677424
(6,) <class 'tuple'>


In [25]:
# create ndarrays from lists
data2 = [[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2))
print (arr2.shape, type(arr2.shape))
result = arr2.tolist()
print (result, len(result), type(result), id(result))

[[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]] 2 <class 'list'> 2911151317248
[[ 11  33  22  55  44  66]
 [100 200 300 400 500 700]] 2 <class 'numpy.ndarray'> 2911146678576
(2, 6) <class 'tuple'>
[[11, 33, 22, 55, 44, 66], [100, 200, 300, 400, 500, 700]] 2 <class 'list'> 2911153756800


In [26]:
# create ndarrays from lists
data2 = [range(1, 5), range(11, 15)]
print (data2, len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2), id(arr2))
print (arr2.shape, type(arr2.shape))
result = arr2.tolist()
print (result, len(result), type(result), id(result))

[range(1, 5), range(11, 15)] 2 <class 'list'> 2911151845056
[[ 1  2  3  4]
 [11 12 13 14]] 2 <class 'numpy.ndarray'> 2911153911632
(2, 4) <class 'tuple'>
[[1, 2, 3, 4], [11, 12, 13, 14]] 2 <class 'list'> 2911151105984


In [35]:
# create ndarrays from lists
data1 = [11, True, 33, False, 22, 55, 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, '55', 44, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, 55, 44.0, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, True, 33, False, 22, '55', 44.0, 66]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, True, 33, False, 22, 55, 44, 66] 8 <class 'list'> 2911151277824
[11  1 33  0 22 55 44 66] 8 <class 'numpy.ndarray'> 2911152022896 int32

[11, True, 33, False, 22, '55', 44, 66] 8 <class 'list'> 2911150934400
['11' 'True' '33' 'False' '22' '55' '44' '66'] 8 <class 'numpy.ndarray'> 2911143716304 <U11

[11, True, 33, False, 22, 55, 44.0, 66] 8 <class 'list'> 2911142055744
[11.  1. 33.  0. 22. 55. 44. 66.] 8 <class 'numpy.ndarray'> 2911152022896 float64

[11, True, 33, False, 22, '55', 44.0, 66] 8 <class 'list'> 2911149997248
['11' 'True' '33' 'False' '22' '55' '44.0' '66'] 8 <class 'numpy.ndarray'> 2911143717840 <U32


In [42]:
# exmining arrays
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1, arr1.shape)
print (arr2, arr2.shape)
print (arr1.dtype, arr2.dtype)
print (arr1.shape, arr2.shape)
print (arr1.ndim, arr2.ndim)
print (arr1.size, arr2.size)    # returns the number of data items
print (len(arr1), len(arr2))    # returns the first dimension

[11 33 22 55 44 66] (6,)
[[ 1  2  3  4]
 [11 12 13 14]] (2, 4)
int32 int32
(6,) (2, 4)
1 2
6 8
6 2


### Create Special Arrays

In [52]:
arr1 = np.zeros(10)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype('int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).reshape(2, 5).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.zeros(10).astype(int).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156382384
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704368
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156382384
[0 0 0 0 0 0 0 0 0 0] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147705040
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156382384
[[0 0 0 0 0]
 [0 0 0 0 0]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156382288
[[0 0 0 0 0]
 [0 0 0 0 0]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911147704944


In [53]:
arr1 = np.ones(10)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype('int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).reshape(2, 5).astype(int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10).astype(int).reshape(2, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156383248
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147705040
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911159970960
[1 1 1 1 1 1 1 1 1 1] 10 10 1 (10,) <class 'numpy.ndarray'> 2911147704944
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911147705040
[[1 1 1 1 1]
 [1 1 1 1 1]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911156383440
[[1 1 1 1 1]
 [1 1 1 1 1]] 2 10 2 (2, 5) <class 'numpy.ndarray'> 2911159970960


In [56]:
arr1 = np.zeros(10) + 5    # vector + scalar
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.ones(10) * 5    # vector * scalar
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911148477296
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 10 10 1 (10,) <class 'numpy.ndarray'> 2911156383632


In [59]:
arr1 = np.linspace(0, 1, 5)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.linspace(0, 10, 11, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.linspace(0, 10, 11, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[0.   0.25 0.5  0.75 1.  ] 5 5 1 (5,) <class 'numpy.ndarray'> 2911156383344
[ 0  1  2  3  4  5  6  7  8  9 10] 11 11 1 (11,) <class 'numpy.ndarray'> 2911156382480
[ 0  1  2  3  4  5  6  7  8  9 10] 11 11 1 (11,) <class 'numpy.ndarray'> 2911156382288


In [62]:
arr1 = np.logspace(0, 3, 4)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.logspace(0, 3, 4, base = 2, dtype = 'int')
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))
arr1 = np.logspace(0, 3, 4, base = 4, dtype = int)
print (arr1, len(arr1), arr1.size, arr1.ndim, arr1.shape, type(arr1), id(arr1))

[   1.   10.  100. 1000.] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148670768
[1 2 4 8] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148669808
[ 1  4 16 64] 4 4 1 (4,) <class 'numpy.ndarray'> 2911148670768


In [67]:
print (np.zeros(20).reshape(5, 4).astype(int).tolist())
print (np.zeros(20).astype(int).reshape(5, 4).tolist())
print (np.zeros(20).astype(int).reshape(4, 5).tolist())

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


### Indexing and Slicing

In [75]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
print (arr1[3], arr1[-3], arr1[1], arr1[-5])    # indexing
print (arr1[3:], arr1[-3:], arr1[:4], arr1[:-2])    # slicing

[11 33 22 55 44 66]
55 55 33 33
[55 44 66] [55 44 66] [11 33 22 55] [11 33 22 55]


In [88]:
data1 = [11, 33, 22, 55, 44, 66, 88, 99, 77, 25, 32, 67, 44, 66, 34, 45]
arr2 = np.array(data1).reshape(4, 4)
print (arr2)
print (arr2[1][2], arr2[-3][-2], arr2[1, 2], arr2[-3, -2])    # indexing
print (arr2[1:3, :])    # slicing
print (arr2[:, 1:3])
print (arr2[1:3, 1:3])
print (arr2[-3:-1, -3:-1])

[[11 33 22 55]
 [44 66 88 99]
 [77 25 32 67]
 [44 66 34 45]]
88 88 88 88
[[44 66 88 99]
 [77 25 32 67]]
[[33 22]
 [66 88]
 [25 32]
 [66 34]]
[[66 88]
 [25 32]]
[[66 88]
 [25 32]]


### Views and Copies

In [91]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr1[2:5] = 100
print (arr1)

[11 33 22 55 44 66]
[ 11  33 100 100 100  66]


In [94]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr_view = arr1[2:5]
print (arr_view)
arr_view[:] = 999
print (arr1)
print (arr_view)
arr1[2:5] = 777
print (arr1)
print (arr_view)

[11 33 22 55 44 66]
[22 55 44]
[ 11  33 999 999 999  66]
[999 999 999]
[ 11  33 777 777 777  66]
[777 777 777]


In [96]:
data1 = [11, 33, 22, 55, 44, 66]
arr1 = np.array(data1)
print (arr1)
arr_copy = arr1[2:5].copy()
print (arr_copy)
arr_copy[:] = 999
print (arr1)
print (arr_copy)
arr1[2:5] = 777
print (arr1)
print (arr_copy)

[11 33 22 55 44 66]
[22 55 44]
[11 33 22 55 44 66]
[999 999 999]
[ 11  33 777 777 777  66]
[999 999 999]


### Boolean Arrays

In [103]:
data1 = [11, 99, 88, 33, 22, 55, 44, 66, 77, 45]
arr1 = np.array(data1)
print (arr1 > 55)
print (arr1[arr1 > 55])
print (~(arr1 > 55))    # negation with ~ operator
print (arr1[~(arr1 > 55)])
print (arr1[arr1 <= 55])

[False  True  True False False False False  True  True False]
[99 88 66 77]
[ True False False  True  True  True  True False False  True]
[11 33 22 55 44 45]
[11 33 22 55 44 45]


In [110]:
data1 = [11, 99, 88, 30, 22, 55, 44, 66, 77, 45]
arr1 = np.array(data1)
print (arr1)
print (arr1 % 6 == 0)
print (arr1[arr1 % 6 == 0])
print ((arr1 % 2 == 0) & (arr1 % 3 == 0))
print (arr1[(arr1 % 2 == 0) & (arr1 % 3 == 0)])
print ((arr1 % 2 == 0) | (arr1 % 3 == 0))
print (arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)])

[11 99 88 30 22 55 44 66 77 45]
[False False False  True False False False  True False False]
[30 66]
[False False False  True False False False  True False False]
[30 66]
[False  True  True  True  True False  True  True False  True]
[99 88 30 22 44 66 45]


In [114]:
data1 = [22, 55, 44, 30, 22, 55, 44, 66, 22, 55]
arr1 = np.array(data1)
print (arr1)
print (np.unique(arr1))

[22 55 44 30 22 55 44 66 22 55]
[22 30 44 55 66]


In [121]:
data1 = ['bob', 'paul', 'jim', 'paul', 'bob', 'tim', 'bob']
arr1 = np.array(data1)
print (arr1)
print (arr1 == 'bob')
print (arr1[arr1 == 'bob'])
print (~(arr1 == 'bob'))
print (arr1[~(arr1 == 'bob')])
arr1[arr1 == 'bob'] = 'pat'
print (arr1)
print (np.unique(arr1))

['bob' 'paul' 'jim' 'paul' 'bob' 'tim' 'bob']
[ True False False False  True False  True]
['bob' 'bob' 'bob']
[False  True  True  True False  True False]
['paul' 'jim' 'paul' 'tim']
['pat' 'paul' 'jim' 'paul' 'pat' 'tim' 'pat']
['jim' 'pat' 'paul' 'tim']


In [122]:
list1 = np.zeros(20).tolist()
print (list1, type(list1))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] <class 'list'>


### Vectorized Operations

In [135]:
nums = np.arange(6)
print (nums, nums.shape)
result = np.sqrt(nums)
print (result)
print (np.ceil(result), np.floor(result), np.isnan(result))
result = np.sum(nums)
print (result)
result = np.mean(nums)
print (result)
result = np.median(nums)
print (result)

[0 1 2 3 4 5] (6,)
[0.         1.         1.41421356 1.73205081 2.         2.23606798]
[0. 1. 2. 2. 2. 3.] [0. 1. 1. 1. 2. 2.] [False False False False False False]
15
2.5
2.5


In [206]:
nums = np.array([100, 200, 400, 300])
print (np.isnan(nums))
nums = np.array([100, np.nan, 200, np.nan, 400, 300])
print (np.isnan(nums))

[False False False False]
[False  True False  True False False]


In [142]:
print (np.maximum(np.array([10, -20, 30, -3, 40, -50]), np.array([15, -40, 32, -1, 33, 10])))
print (np.minimum(np.array([10, -20, 30, -3, 40, -50]), np.array([15, -40, 32, -1, 33, 10])))

[ 15 -20  32  -1  40  10]
[ 10 -40  30  -3  33 -50]


### Dealing with Numpy Random Numbers

In [153]:
vect1 = np.random.randn(100000)     # random numbers normalized, here the average of numbers will be 0 and std will be 1
print (vect1, len(vect1))
print (np.mean(vect1), np.std(vect1))

[-0.53321862 -0.54350446 -0.29509252 ...  1.64774944  0.20079714
  0.04330835] 100000
-6.352128808915075e-05 1.0003560125311275


In [ ]:
pt1 (x1, y1)
pt2 (x2, y2)
dist_eucledian = sqrt((x1 - x2)^2 + (y1 - y2)^2)

pt1 (x1, x2, x3, x4)
pt2 (y1, y2, y3, y4)
dist_eucledian = sqrt((x1 - y1)^2 + (x2 - y2)^2 + (x3 - y3)^2 + (x4 - y4)^2)

In [173]:
# calculating Eucledian distance between two vectors
vect1 = np.random.randn(10)
vect2 = np.random.randn(10)
print (vect1, vect1.shape, type(vect1))
print (vect2, vect2.shape, type(vect2))

eucledian_dist = 0
for i in range(len(vect1)):
    eucledian_dist = eucledian_dist + (vect1[i] - vect2[i]) ** 2
print (np.sqrt(eucledian_dist))

print (np.sqrt(np.sum((vect1 - vect2) ** 2)))
print (np.sqrt(np.sum(pow(np.subtract(vect1, vect2), 2))))
print (np.linalg.norm(vect1 - vect2))
print (np.linalg.norm(np.subtract(vect1, vect2)))

[-0.03588112  2.6109494  -0.08664161  2.36596562  1.14770948  0.32181776
 -1.44555277 -1.25693384 -2.05955137 -1.07850976] (10,) <class 'numpy.ndarray'>
[-0.2086692  -0.01387183  0.98798743 -0.66613037  1.19039588 -1.5397081
  0.75419873 -1.11965114  2.1388429  -0.80946185] (10,) <class 'numpy.ndarray'>
6.57964520384926
6.57964520384926
6.57964520384926
6.57964520384926
6.57964520384926


In [179]:
vect1 = np.random.randn(10)
print (vect1, vect1.shape, type(vect1))
print (vect1 >= 0)
print ((vect1 >= 0).sum())
print ((vect1 >= 0).any())
print ((vect1 >= 0).all())

[ 0.95331872  0.77995747  0.37905931 -0.97568079 -0.40331077 -0.02286105
 -2.04870396  0.02065024 -0.62499273  0.66249163] (10,) <class 'numpy.ndarray'>
[ True  True  True False False False False  True False  True]
5
True
False


In [183]:
rnd = np.random.randn(12)
print (rnd)
rnd = np.random.randn(4, 3)
print (rnd)
rnd = np.random.randn(12).reshape(4, 3)
print (rnd)
rnd = np.random.randn(12).reshape(3, 2, 2)
print (rnd)

[-0.2141626  -0.20913675 -0.34351493 -1.64499648  1.87593584 -2.00445566
  1.02509298 -0.7642748  -0.9431635  -1.09012847  1.95942734  0.67737936]
[[-1.36586755  1.51336679  0.10472577]
 [ 1.8728379   0.03505361  0.65958067]
 [-0.68029961 -0.47722208 -0.27633896]
 [ 0.49724401  0.43754669 -1.20317615]]
[[ 0.78599051 -2.10491599 -0.25483446]
 [-0.93015277 -1.2483377   0.04315336]
 [ 0.19914648 -0.02370458  0.07711737]
 [-0.36608704  0.40508896  2.29534195]]
[[[-0.11146134 -1.97268832]
  [ 0.96250275  0.19131133]]

 [[-0.58927252  0.2278398 ]
  [ 1.19699973  0.71582402]]

 [[-1.31176697 -0.70370837]
  [ 1.43093397 -0.13149862]]]


In [186]:
rnd = np.random.randn(6)
print (rnd)
print (np.mean(rnd))
print (np.std(rnd))
print (np.sum(rnd))
print (np.argmax(rnd))
print (np.argmin(rnd))

[-0.37431936  0.43277132 -0.40267548  0.32092194 -0.16506549  0.24590415]
0.009589515419849981
0.33657791387216696
0.057537092519099886
1
2


In [195]:
rnd = np.random.randn(4, 3)
print (rnd)
print (np.mean(rnd))
print (np.std(rnd))
print (np.sum(rnd), rnd.sum())
print (np.argmax(rnd))
print (np.argmin(rnd))
print (rnd.sum())
print (rnd.sum(axis = 0))    # columnwise sum
print (rnd.sum(axis = 1))    # rowwise sum

[[-0.03098009 -0.06563844 -1.07331886]
 [ 0.21445505 -1.77979603  1.09303111]
 [-0.43077731  0.54205725 -0.29123415]
 [ 0.4460891   0.19586936  1.07679996]]
-0.00862025319005714
0.7919302714974664
-0.10344303828068568 -0.10344303828068568
5
4
-0.10344303828068568
[ 0.19878676 -1.10750786  0.80527806]
[-1.16993739 -0.47230986 -0.17995421  1.71875842]


In [ ]:
help(np)

In [202]:
nums = np.arange(32).reshape(8, 4)
print (nums)
print (nums.shape)
result = nums.T    # Transpose
print (result)
print (result.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
(8, 4)
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
(4, 8)


In [204]:
nums = np.arange(32).reshape(8, 4)
print (nums)
print (nums.shape)
result = nums.flatten()
print (result)
print (result.shape)
result = nums.T    # Transpose
print (result)
print (result.shape)
result = result.flatten()
print (result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
(8, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
(32,)
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
(4, 8)
[ 0  4  8 12 16 20 24 28  1  5  9 13 17 21 25 29  2  6 10 14 18 22 26 30
  3  7 11 15 19 23 27 31]


### Ndarray in Row and Column Major Ways

In [215]:
# matrix = np.array([10, 50, 20, 60, 40, 100, 34, 21, 12, 100], dtype = float).reshape(2, 5)
matrix = np.arange(10, dtype = float).reshape(2, 5)
print (matrix)

print ("\nSorted in C-style order (Row Major):")
cmatrix = matrix.copy(order = 'C')
print (cmatrix)
for x in np.nditer(cmatrix):
    print (x, end = ", ")
print ()
print ("\nSorted in F-style order (Column Major):")
fmatrix = matrix.copy(order = 'F')
print (fmatrix)
for x in np.nditer(fmatrix):
    print (x, end = ", ")
print ()

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

Sorted in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

Sorted in F-style order (Column Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 


### Append, Insert, Delete and Sort

In [231]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, matrix.shape)
matrix = np.append(matrix, [10, 11, 12, 13])
print (matrix, matrix.shape)
matrix = np.insert(matrix, 3, [14, 15, 16])
print (matrix, matrix.shape)
matrix = np.delete(matrix, [5, 6, 7])
print (matrix, matrix.shape)
matrix = np.delete(matrix, range(5, 8))
print (matrix, matrix.shape)
matrix = np.sort(matrix)
print (matrix, matrix.shape)
matrix = -np.sort(-matrix)
print (matrix, matrix.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] (14,)
[ 0  1  2 14 15 16  3  4  5  6  7  8  9 10 11 12 13] (17,)
[ 0  1  2 14 15  5  6  7  8  9 10 11 12 13] (14,)
[ 0  1  2 14 15  8  9 10 11 12 13] (11,)
[ 0  1  2  8  9 10 11 12 13 14 15] (11,)
[15 14 13 12 11 10  9  8  2  1  0] (11,)


### Concatenating two Matrices

In [234]:
matrix1 = np.array([[1, 2], [3, 4]])
print ("First array:")
print (matrix1)
print ()

matrix2 = np.array([[5, 6], [7, 8]])
print ("Second array:")
print (matrix2)
print ()

# both the arrays are of the same dimensions
print ("Joining the two arrays long axis 0:")
result = np.concatenate((matrix1, matrix2))
print (result)
print ()
print ("Joining the two arrays long axis 1:")
result = np.concatenate((matrix1, matrix2), axis = 1)
print (result)

First array:
[[1 2]
 [3 4]]

Second array:
[[5 6]
 [7 8]]

Joining the two arrays long axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joining the two arrays long axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [236]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("First array:")
print (matrix1)
print ()

matrix2 = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print ("Second array:")
print (matrix2)
print ()

# both the arrays are of the same dimensions
print ("Joining the two arrays long axis 0:")
result = np.concatenate((matrix1, matrix2))
print (result)
print ()
print ("Joining the two arrays long axis 1:")
result = np.concatenate((matrix1, matrix2), axis = 1)
print (result)

First array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second array:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Joining the two arrays long axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]

Joining the two arrays long axis 1:
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]


In [237]:
print ("Stack the two arrays along axis 0:")
result = np.stack((matrix1, matrix2), 0)
print (result)
print ()

Stack the two arrays along axis 0:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]

