### PANDAS: INTRODUCTION

> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section focuses on a small, but important aspect of data manipulation and cleaning with Pandas.

### Data Structures

**There are two data structures are there in Pandas -**<br>
* **Series -** It is one-dimensional labeled array capable of holding any data type (integer, strings, floating point numbers, Python objects etc.) of data. The axis is collectively referred to as index.

* **Data Frame -** It is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL Table or a Series of objects.

### Series Data Structure:

**pandas.core.series.Series(data, index, dtype, copy)**<br>
* **data -** data takes various forms like ndarray, list, constants, dictionary etc.<br>
* **index -** it is unique and hashable for easy identification.<br>
* **dtype -** it is for data type.<br>
* **copy -** copy data, and its default value is False. It only affects for Series or one dimensional ndarray inputs.

In [1]:
# importing required modules
import pandas as pd
import numpy as np

In [2]:
# creating empty Series
s = pd.Series()
print (s, type(s))

Series([], dtype: float64) <class 'pandas.core.series.Series'>


<ipython-input-2-2a82def5a837>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [9]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data)
print (s)
print (type(s))
print (s[0], s[3])

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
0        apple
1       banana
2       cherry
3    pineapple
dtype: object
<class 'pandas.core.series.Series'>
apple pineapple


In [7]:
arr_data = np.array([100, 300, 200, 600, 500])
s = pd.Series(arr_data, copy = False)
print (arr_data, type(arr_data))
print (s, type(s))
s[0] = 999
arr_data[2] = 888
print (arr_data, type(arr_data))
print (s, type(s))

[100 300 200 600 500] <class 'numpy.ndarray'>
0    100
1    300
2    200
3    600
4    500
dtype: int32 <class 'pandas.core.series.Series'>
[999 300 888 600 500] <class 'numpy.ndarray'>
0    999
1    300
2    888
3    600
4    500
dtype: int32 <class 'pandas.core.series.Series'>


In [8]:
arr_data = np.array([100, 300, 200, 600, 500])
s = pd.Series(arr_data, copy = True)
print (arr_data, type(arr_data))
print (s, type(s))
s[0] = 999
arr_data[2] = 888
print (arr_data, type(arr_data))
print (s, type(s))

[100 300 200 600 500] <class 'numpy.ndarray'>
0    100
1    300
2    200
3    600
4    500
dtype: int32 <class 'pandas.core.series.Series'>
[100 300 888 600 500] <class 'numpy.ndarray'>
0    999
1    300
2    200
3    600
4    500
dtype: int32 <class 'pandas.core.series.Series'>


In [15]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = [100, 101, 102, 103])
print (s)
print (type(s))
print (s[100], type(s[100]), s[103], type(s[103]))

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
100        apple
101       banana
102       cherry
103    pineapple
dtype: object
<class 'pandas.core.series.Series'>
apple <class 'str'> pineapple <class 'str'>


In [14]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = [100, 103, 100, 103])
print (s)
print (type(s))
print (s[100])
print (s[103])

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
100        apple
103       banana
100       cherry
103    pineapple
dtype: object
<class 'pandas.core.series.Series'>
100     apple
100    cherry
dtype: object
103       banana
103    pineapple
dtype: object


### Data Frame Data Structure: